@startuml
class IAction <<interface>> {
   + execute (const IMessage&, IContext&, IDocument&) : void

}

class ILoadAction <<abstract>> {
}

class ISaveAction <<abstract>> {
}

class IEditAction <<abstract>> {
}

class CreateDocumentAction{}

class SaveXMLAction{}
class SaveJsonAction{}

class LoadXMLAction{}
class LoadJsonAction{}

class AddPrimitiveAction{}
class DelPrimitiveAction{}


IAction <|.. ILoadAction
IAction <|.. ISaveAction
IAction <|.. IEditAction
IAction <|.. CreateDocumentAction


ISaveAction <|-- SaveXMLAction
ISaveAction <|-- SaveJsonAction

ILoadAction <|-- LoadXMLAction
ILoadAction <|-- LoadJsonAction

IEditAction <|-- AddPrimitiveAction
IEditAction <|-- DelPrimitiveAction

@enduml