@startuml

title Controler

class IController <<interface>> {
}

class Controller {
  - m_document : unique_ptr<IDocument>
  - m_context : unique_ptr<EditContext>
  - m_view : shared_ptr<IDocument>
}

class IView <<interface>> {
 
}

class IDocument <<interface>> {
 
}

class IContext <<interface>> {
 
}

class IAction <<interface>> {
 
}




Controller --> IView : shared_ptr
IView ..> Controller : weak_ptr
IController <|-- Controller
Controller -> IDocument : unique_ptr
Controller -> IContext : unique_ptr
Controller ..> IAction : Maps the IMessage to an IAction 

'class AddPrimitiveAction {}
'class RemovePrimitiveAction {}
'class CompositeAction {}

'IAction <|-- AddPrimitiveAction
'IAction <|-- RemovePrimitiveAction
'IAction <|-- CompositeAction



@enduml