@startuml

class IContext<<interface>>{
  + {abstract} get_selection() const : const selection_t&;
  + {abstract} set_selection(const selection_t&): void;   
  
  + {abstract} get_primitive() const :const IPrimitive&    
  + {abstract} set_primitive(const IPrimitive&) :void    
} 

class IPrimitive<<interface>>{
} 

class CharPrimitive{
} 

class ShapePrimitive{
} 


class selection_t{
  +m_start: size_t;
  +m_end: size_t;
} 

IContext --> IPrimitive
IContext --> selection_t

IPrimitive <|-- CharPrimitive
IPrimitive <|-- ShapePrimitive


@enduml