@startuml

class IContext<<interface>>{
  + {abstract} get_selection() const : const ISelection&;
  + {abstract} set_selection(const ISelection&): void;   
  
  + {abstract} get_primitive() const :const IPrimitive&    
  + {abstract} set_primitive(const IPrimitive&) :void    
} 

class IPrimitive<<interface>>{
} 

class CharPrimitive{
} 

class ShapePrimitive{
} 

class ISelection<<interface>>{} 
class SimpleSelection{
  -m_selection: std::pair<siz_t, sise_t>;
  +get() const : std::pair<siz_t, sise_t>
  set(const std::pair<siz_t, sise_t> &) : void

} 

IContext --> IPrimitive
IContext --> ISelection

IPrimitive <|-- CharPrimitive
IPrimitive <|-- ShapePrimitive

ISelection <|-- SimpleSelection

@enduml