@startuml
title Interfaces
class IController <<interface>> {
  + {abstract} get_document() const : const IDocumednt&
  + {abstract} process_message(msg: const IMessage& ) const :void 
 }

class IView<<interface>>{
  + {abstract} show (document: const IDocument &document) const : void
  + {abstract} notify_сontroller(msg: const IMessage& ) const :void 
}
class IDocument <<interface>>{}
class IMessage<<interface>>{} 
class IContext <<interface>>{}

class IAction<<interface>>
{
      + execute (message: const IMessage&, context: IContext&, document: IDocument&
  ) : void
} 


IMessage <.. IAction : Input
IAction <..> IContext : Input/Output
IAction <..> IDocument : Input/Output

IView ..> IMessage : Notify Controller
IView ..> IDocument : Show
IController ..> IMessage : Process
IController ..> IDocument : Containes


@enduml