@startuml
title Interfaces: IDocument is a Model, IView and IController - View and Controller in MVC
class IController <<interface>> #LightGreen {
  + {abstract} get_document() const : const IDocumednt&
  + {abstract} process_message(msg: const IMessage& ) const :void 
 }

class IView<<interface>> #LightGreen {
  + {abstract} show (const IDocument &) const : void
  + {abstract} notify_сontroller(const IMessage& ) const :void 
}
class IDocument <<interface>> #LightGreen {}
class IMessage<<interface>>{
} 

enum MessageType{}

class IContext <<interface>>{}

class IAction<<interface>>
{
   + execute (const IMessage&, IContext&, IDocument&) : void
} 

class IActionFactory <<interface>>{
  + create(MessageType): unique_ptr<IAction>
}

IMessage <.. IAction : Input
IAction <..> IContext : Input/Output
IAction <..> IDocument : Input/Output

IView ..> IMessage : Notify Controller
IView ..> IDocument : Show
IController ..> IMessage : Process
IController-> IDocument : Containes
IMessage-->MessageType
IActionFactory..>IAction : creates
IActionFactory..>MessageType : input
IController..>IActionFactory : init_actions
IController->IView
@enduml