var annotated_dup =
[
    [ "ActionFactory", "de/d10/classActionFactory.html", "de/d10/classActionFactory" ],
    [ "AddPrimitiveAction", "dc/ded/classAddPrimitiveAction.html", "dc/ded/classAddPrimitiveAction" ],
    [ "CharPrimitive", "dc/d93/classCharPrimitive.html", null ],
    [ "Context", "d2/d00/classContext.html", "d2/d00/classContext" ],
    [ "Controller", "d9/d85/classController.html", "d9/d85/classController" ],
    [ "CreateDocumentAction", "d5/da2/classCreateDocumentAction.html", "d5/da2/classCreateDocumentAction" ],
    [ "DelPrimitiveAction", "de/d1c/classDelPrimitiveAction.html", "de/d1c/classDelPrimitiveAction" ],
    [ "Document", "d1/d67/classDocument.html", null ],
    [ "IAction", "df/dc6/classIAction.html", "df/dc6/classIAction" ],
    [ "IActionFactory", "d5/d12/classIActionFactory.html", "d5/d12/classIActionFactory" ],
    [ "IContext", "d4/d88/classIContext.html", "d4/d88/classIContext" ],
    [ "IController", "df/d87/classIController.html", "df/d87/classIController" ],
    [ "IDocument", "dd/d3a/classIDocument.html", null ],
    [ "IEditAction", "d9/dee/classIEditAction.html", null ],
    [ "ILoadAction", "db/d3e/classILoadAction.html", null ],
    [ "IMessage", "d6/d68/classIMessage.html", "d6/d68/classIMessage" ],
    [ "IPrimitive", "d6/d4d/classIPrimitive.html", null ],
    [ "ISaveAction", "dc/d62/classISaveAction.html", null ],
    [ "IView", "df/d1c/classIView.html", "df/d1c/classIView" ],
    [ "LoadJsonAction", "dc/d82/classLoadJsonAction.html", "dc/d82/classLoadJsonAction" ],
    [ "LoadXMLAction", "da/d72/classLoadXMLAction.html", "da/d72/classLoadXMLAction" ],
    [ "Message", "d6/d28/classMessage.html", "d6/d28/classMessage" ],
    [ "SaveJsonAction", "d7/d82/classSaveJsonAction.html", "d7/d82/classSaveJsonAction" ],
    [ "SaveXMLAction", "d7/db8/classSaveXMLAction.html", "d7/db8/classSaveXMLAction" ],
    [ "ShapePrimitive", "da/d6b/classShapePrimitive.html", null ],
    [ "View", "d7/d9f/classView.html", "d7/d9f/classView" ]
];