name: Generate UML Diagrams

on:
  push:
    branches: [ Editor ]
    paths: [ 'doc/uml/src/**' ]

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate UML
        uses: grassedge/generate-plantuml-action@v1
        with:
          image-format: 'png'
          path: 'plant_uml'
          output: 'docs/uml/images'
          
      - name: Commit generated UML
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/uml/images/
          git commit -m "Update UML diagrams" || exit 0
          git push