name: Deploy Editor Docs

on:
  push:
    branches:
      - Editor
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate and deploy Doxygen docs
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: Editor
          doxygen-version: 1.9.6
          deploy-branch: gh-pages
          deploy-folder: docs